# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-19 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meizi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meizis',
            name='img_url',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='meizis',
            name='mid',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='meizis',
            name='page_url',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='meizis',
            name='picname',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='meizis',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
